<a href="https://colab.research.google.com/github/adityaas26/Deep-Learning/blob/master/Part_1_Tensors_in_PyTorch_(Exercises).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

In [0]:
def activation(x):
    """ Sigmoid activation function 
    
        Arguments
        ---------
        x: torch.Tensor
    """
    return 1/(1+torch.exp(-x))
  

In [0]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 5))
# True weights for our data, random normal variables again
weights = torch.randn_like(features)
# and a true bias term
bias = torch.randn((1, 1))

In [0]:
# Calculate the output of this network using the weights and bias tensors

print(features * weights)

res = activation(torch.sum(features * weights) + bias)
print(res)

tensor([[ 0.1314, -0.2796,  1.1668, -0.1540, -2.8442]])
tensor([[0.1595]])


In [0]:
features.shape
weights.shape

torch.Size([1, 5])

In [0]:
# Calculate the output of this network using matrix multiplication

weights.view(5,1)
# torch.mm(features, weights.view(5,1))
res = activation(torch.mm(features, weights.view(5,1)) + bias)
print(res)

tensor([[0.1595]])


In [0]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 3))

# Define the size of each layer in our network
n_input = features.shape[1]     # Number of input units, must match number of input features
n_hidden = 2                    # Number of hidden units 
n_output = 1                    # Number of output units

# Weights for inputs to hidden layer
W1 = torch.randn(n_input, n_hidden)
# Weights for hidden layer to output layer
W2 = torch.randn(n_hidden, n_output)

# and bias terms for hidden and output layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

In [0]:
h1 = torch.mm(features, W1)
print(h1)

res1 = activation(h1 + B1)
print(res1)

h2 = torch.mm(res1, W2)
print(h2)

res2 = activation(h2 + B2)
print(res2)  

tensor([[ 0.6270, -0.3969]])
tensor([[0.6813, 0.4355]])
tensor([[-1.0078]])
tensor([[0.3171]])
